<a href="https://colab.research.google.com/github/Harun-Githinji/harun-repo/blob/main/harun_githinji_SQL_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [2]:
%%sql

SELECT
   *
FROM
  Sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199868,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
199869,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
199870,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
199871,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
199872,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38

In [6]:
%%sql

SELECT
   *
FROM
 Customer
Limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,15,4,1990-09-10,2034-07-29,Australia,male,Mr.,Julian,A,McGuigan,...,4357,AU,Australia,1965-03-24,55,Border Patrol agent,Cut Rite Lawn Care,2000 Peugeot Kart Up,-27.83,151.17
1,23,8,1995-08-11,2045-01-26,Australia,female,Ms.,Rose,H,Dash,...,6055,AU,Australia,1990-05-10,30,Agricultural and food scientist,Rack N Sack,2005 Volvo XC90,-31.92,116.05
2,36,2,1992-03-12,2044-05-14,Australia,female,Ms.,Annabelle,J,Townsend,...,2304,AU,Australia,1964-07-16,56,Special education teacher,id Boutiques,1999 Lancia Lybra,-32.88,151.71
3,120,6,1983-07-23,2033-08-09,Australia,male,Mr.,Jamie,H,Hetherington,...,7256,AU,Australia,1946-12-11,74,Dental laboratory technician,Showbiz Pizza Place,2006 Dodge Durango,-39.77,144.02
4,180,7,1987-11-26,2026-10-14,Australia,male,Mr.,Gabriel,P,Bosanquet,...,3505,AU,Australia,1955-04-24,65,Administrative support specialist,Dubrow's Cafeteria,1995 Morgan Plus 4,-34.13,142.14
5,185,2,1990-08-01,2029-05-28,Australia,female,Mrs.,Gabrielle,B,Castella,...,2469,AU,Australia,1980-02-23,40,Management dietitian,d.e.m.o.,1997 Alpina B6,-29.01,152.84
6,189,7,2008-07-05,2017-11-01,Australia,female,Ms.,Hayley,C,Jull,...,3377,AU,Australia,1960-04-18,60,Sculptor,Asian Plan,2006 Alpina B5,-37.34,142.91
7,210,2,1980-09-28,2030-05-08,Australia,female,Mrs.,Natalie,L,Hilder,...,2632,AU,Australia,1950-11-23,70,Motel desk clerk,Enrich Garden Services,1995 Ford Fairlane,-36.84,149.05
8,225,7,1985-06-25,2017-09-25,Australia,male,Mr.,Hunter,J,Hutchins,...,3763,AU,Australia,1978-07-20,42,Teletype operator,Mr. Good Buys,2012 Lexus GX,-37.51,145.44
9,243,2,1982-02-07,2027-02-09,Australia,female,Ms.,Maya,J,Atherton,...,2446,AU,Australia,1954-05-15,66,Pilates instructor,Franklin Music,1995 Chevrolet Caprice,-31.36,152.39

Using aggregate functions

Reecent Sales >=2020

In [5]:
%%sql

SELECT
  orderdate,
  quantity * netprice * exchangerate  AS Net_revenue
FROM
  Sales
WHERE
  orderdate >= '2020-01-01'
Order by
  net_revenue asc
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2023-02-02         0.75
1  2024-02-02         0.79
2  2022-08-09         0.83
3  2023-08-08         0.87
4  2023-11-15         0.87
5  2022-08-13         0.88
6  2023-02-24         0.90
7  2022-10-27         0.93
8  2023-11-21         0.95
9  2022-12-26         0.95

USING LEFT JOIN IN THE QUERIES

In [11]:
%%sql

SELECT
  s.orderdate,
  p.productname,
  CONCAT(c.givenname, ' ', c.surname) AS Customer_name,
  s.quantity * s.netprice * s.exchangerate  AS Net_revenue
FROM
  Sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
LEFT JOIN product p ON s.productkey = p.productkey
WHERE
  orderdate >= '2020-01-01'
Order by
  net_revenue asc
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,productname,customer_name,net_revenue
0,2023-02-02,SV USB Data Cable E600 Silver,Ouassima van Zutphen,0.75
1,2024-02-02,SV USB Data Cable E600 Grey,Generosa Fanucci,0.79
2,2022-08-09,SV USB Data Cable E600 Silver,Adela Long,0.83
3,2023-08-08,SV USB Data Cable E600 Silver,Dominik Werner,0.87
4,2023-11-15,SV USB Data Cable E600 Pink,Jonas Kirsch,0.87
5,2022-08-13,SV USB Data Cable E600 Silver,Azura Pouchard,0.88
6,2023-02-24,SV USB Data Cable E600 Pink,Julian Freeman,0.90
7,2022-10-27,SV USB Data Cable E600 Pink,Mike Thompson,0.93
8,2023-11-21,SV USB Data Cable E600 Pink,Billy Vasbinder,0.95
9,2022-12-26,SV USB Data Cable E600 Pink,Daniel Baca,0.95

In [19]:
%%sql

SELECT
  s.orderdate,
  p.productname,
  CONCAT(c.givenname, ' ', c.surname) AS Customer_name,
  s.quantity * s.netprice * s.exchangerate  AS Net_revenue,
  CASE WHEN s.quantity * s.netprice * s.exchangerate > 1000 THEN 'High Revenue'
  ELSE 'Low Revenue' END AS Revenue_Category
FROM
  Sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
LEFT JOIN product p ON s.productkey = p.productkey
WHERE
  s.orderdate::date>='2020-01-01'
Order by
  net_revenue asc
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,productname,customer_name,net_revenue,revenue_category
0,2023-02-02,SV USB Data Cable E600 Silver,Ouassima van Zutphen,0.75,Low Revenue
1,2024-02-02,SV USB Data Cable E600 Grey,Generosa Fanucci,0.79,Low Revenue
2,2022-08-09,SV USB Data Cable E600 Silver,Adela Long,0.83,Low Revenue
3,2023-08-08,SV USB Data Cable E600 Silver,Dominik Werner,0.87,Low Revenue
4,2023-11-15,SV USB Data Cable E600 Pink,Jonas Kirsch,0.87,Low Revenue
5,2022-08-13,SV USB Data Cable E600 Silver,Azura Pouchard,0.88,Low Revenue
6,2023-02-24,SV USB Data Cable E600 Pink,Julian Freeman,0.90,Low Revenue
7,2022-10-27,SV USB Data Cable E600 Pink,Mike Thompson,0.93,Low Revenue
8,2022-12-26,SV USB Data Cable E600 Pink,Daniel Baca,0.95,Low Revenue
9,2023-11-21,SV USB Data Cable E600 Pink,Billy Vasbinder,0.95,Low Revenue

COUNT (DISTINCT)

Total customers per day in 2023

In [26]:
%%sql

SELECT
  s.orderdate,
  CONCAT(c.givenname,' ',c.surname) AS Customer_name,
  COUNT(DISTINCT s.customerkey) AS Customer_count
FROM
  Sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
WHERE
  orderdate >= '2023-01-01'
Group by
  orderdate,
  Customer_name
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate          customer_name  customer_count
0  2023-01-01            Arnou Lebel               1
1  2023-01-01          Arthur Lesage               1
2  2023-01-01  Christopher Messenger               1
3  2023-01-01       Evelyn Hernandez               1
4  2023-01-01        Geraldine Spade               1
5  2023-01-01            Jamie Moore               1
6  2023-01-01          Julia Monahan               1
7  2023-01-01             Lea Kortig               1
8  2023-01-01           Liane Chalut               1
9  2023-01-01           Rosa Haggard               1

Daily Customers by Region

In [27]:
%%sql

SELECT DISTINCT
  continent
FROM
  customer

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

       continent
0         Europe
1  North America
2      Australia

In [30]:
%%sql

SELECT
  s.orderdate,
  CONCAT(c.givenname,' ',c.surname) AS Customer_name,
  COUNT(DISTINCT CASE WHEN c.continent = 'Europe' THEN s.customerkey END) AS Europe_count,
  COUNT(DISTINCT CASE WHEN c.continent = 'North America' THEN s.customerkey END) AS North_America_count,
  COUNT(DISTINCT CASE WHEN c.continent = 'Australia' THEN s.customerkey END) AS Australia_count
FROM
  Sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
Group by
  orderdate,
  Customer_name
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,customer_name,europe_count,north_america_count,australia_count
0,2015-01-01,Beverly Tejeda,0,1,0
1,2015-01-01,Hayden Rowe,1,0,0
2,2015-01-01,Hope McNeil,0,1,0
3,2015-01-01,Jack Gabor,0,1,0
4,2015-01-01,Kristi Daniel,0,1,0
5,2015-01-01,Leo Miller,1,0,0
6,2015-01-01,Oliver Warner,1,0,0
7,2015-01-01,Richard Holland,0,1,0
8,2015-01-01,Ruth Hillman,0,1,0
9,2015-01-02,Antígona Guerra,0,1,0

Total net revenue by Category

In [34]:
%%sql

SELECT
  p.categoryname,
  SUM(s.quantity * s.netprice * s.exchangerate) AS Total_revenue,
  SUM(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
    THEN s.quantity * s.netprice * s.exchangerate ELSE NULL END) AS Revenue_2022,
  SUM(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
    THEN s.quantity * s.netprice * s.exchangerate ELSE NULL END) AS Revenue_2023
FROM
  Sales s
LEFT JOIN product p ON s.productkey = p.productkey
Group by
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  total_revenue  revenue_2022  revenue_2023
0                          Audio     5312898.10     766938.21     688690.18
1        Cameras and camcorders     18520360.66    2382532.56    1983546.29
2                    Cell phones    32624265.72    8119665.07    6002147.63
3                      Computers    90619022.05   17862213.49   11650867.21
4                 Games and Toys     1668574.13     316127.30     270374.96
5                Home Appliances    26607245.54    6612446.68    5919992.87
6  Music, Movies and Audio Books    10588311.00    2989297.28    2180768.13
7                   TV and Video    20466861.38    5815336.61    4412178.23

Statistical Functions

In [35]:
%%sql

SELECT
  orderdate,
  PERCENTILE (0.5) WITHIN GROUP (ORDER BY netprice) as median_price
FROM
  sales
Group by
  orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

RuntimeError: (The named parameters feature is "disabled". Enable it with: %config SqlMagic.named_parameters="enabled".
For more info, see the docs: https://jupysql.ploomber.io/en/latest/api/configuration.html#named-parameters)
(psycopg2.errors.UndefinedFunction) function percentile(numeric, double precision) does not exist
LINE 3:   PERCENTILE (0.5) WITHIN GROUP (ORDER BY netprice) as media...
          ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL: SELECT
  orderdate,
  PERCENTILE (0.5) WITHIN GROUP (ORDER BY netprice) as median_price
FROM
  sales
Group by
  orderdate]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
%%sql

SELECT
  p.categoryname AS Category,
  PERCENTILE_CONT (.5)